Repository equinor/everest, pull requests merged in 2024-06, with the labels that each got.

#32 Add file with perturbation results
  everest/suite.py
Labels: enhancement

#39 Accept the new everest-models hook for linting forward models
  everest/config/validation_utils.py
  everest/plugins/hook_impl.py
  everest/plugins/hook_specs.py
  everest/util/forward_models.py
  tests/test_fm_plugins.py
Labels: bug, enhancement

#37 Handle case for no local DNS more properly
  everest/detached/jobs/everserver.py
Labels: bug

#42 Fix how everest handels everest-models plugin hook
  everest/util/forward_models.py
  tests/conftest.py
  tests/test_data/open_shut_state_modifier/eclipse/model/EXPECTED.SCH
  tests/test_data/open_shut_state_modifier/eclipse/model/INIT.SCH
  tests/test_data/open_shut_state_modifier/eclipse/realizations/real-1/R1_ECL_MODEL.DATA
  tests/test_data/open_shut_state_modifier/everest/input/files/add_templates.yml
  tests/test_data/open_shut_state_modifier/everest/input/files/well_swap_config.yml
  tests/test_data/open_shut_state_modifier/everest/input/templates/welopen.jinja
  tests/test_data/open_shut_state_modifier/everest/input/templates/welshut.jinja
  tests/test_data/open_shut_state_modifier/everest/model/index.yml
  tests/test_workflows.py
Labels: bug, enhancement
